id = "wakatime"
name = "Wakatime"
version = "0.1.0"
schema_version = 1
authors = ["Ewen Le Bihan <hey@ewen.works>", "Rodney Osodo <socials@rodneyosodo.com>"]
description = "Automatic time tracking via https://wakatime.com"
repository = "https://github.com/ewen-lbh/zed-wakatime"

[language_servers.wakatime]
name = "Wakatime LSP"
# Taken from https://github.com/zed-industries/zed/blob/efc2336be5dd352961765398350fc2fe10f15345/extensions/snippets/extension.toml#L11-L15
languages = [
    "Astro",
    "Clojure",
    "C",
    "C++",
    "C#",
    "Dart",
    "Dockerfile",
    "Elixir",
    "Elm",
    "ERB",
    "Erlang",
    "Gleam",
    "GLSL",
    "Go",
    "Haskell",
    "HCL",
    "HEEX",
    "HTML",
    "JavaScript",
    "JSDoc",
    "JSON",
    "Lua",
    "Markdown",
    "OCaml",
    "PHP",
    "Python",
    "Prisma",
    "PureScript",
    "Racket",
    "Ruby",
    "Rust",
    "Scheme",
    "Shell Script",
    "Svelte",
    "Terraform",
    "TOML",
    "TypeScript",
    "TSX",
    "Uiua",
    "Vue.js",
    "Zig",
    "LOG"
]
language_ids = { TypeScript = "typescript", TSX = "typescriptreact", JavaScript = "javascript", "Vue.js" = "vue", Terraform = "terraform", "Terraform Vars" = "terraform-vars", PHP = "php", HTML = "html", CSS = "css", LOG = "log" }
